<?php
    /**
     * @file
     * Contains jiscfe_theme.
     */
    declare(strict_types=0);
    
    use Drupal\Core\Form\FormStateInterface;
    use Drupal\Core\Template\Attribute;
    
    
    /**
     * Implements hook_theme().
     *
     * @param $existing
     * @param $type
     * @param $theme
     * @param $path
     *
     * @return array
     */
    function jiscfe_theme($existing, $type, $theme, $path) {
        return [];
    }